name: common_bloc_lyrics
description: Shared Code between AngularDart and Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  equatable: ^0.2.0
  http: ^0.12.0
  bloc: ^2.0.0
